### PR TITLE
Dataset upload

### LINKED ISSUE #24: LibraryChecker is using a hardcoded path
LibraryChecker.cs refers to a hardcoded path:

```Assets/Placenote/Plugins/iOS/Placenote.framework/Placenote```

Which fails when the package is installed elsewhere.

### PR DESCRIPTION
**Pull request by pmukherj**
Add ability to upload dataset and fix #24

### CODE REVIEW

File: Assets/Placenote/Editor/LibraryCheck.cs [hunk 1]
```diff
@@ -1,16 +1,25 @@
 ﻿using System.IO;
+using System.Linq;
 using UnityEngine;
 using UnityEditor;
 using UnityEditor.Build;
 
-class LibraryCheck : IPreprocessBuild
+
+class LibraryCheck : ScriptableObject, IPreprocessBuild
```
Comment (y22ma) [inline Assets/Placenote/Editor/LibraryCheck.cs:8]: Very nice!

File: Assets/Placenote/Examples/PlacenoteSampleView.cs [hunk 2]
```diff
@@ -221,6 +225,22 @@ public void OnLoadMapClicked ()
...
+					if (mReportDebug) {
+						LibPlacenote.Instance.StartRecordDataset (
+							(datasetCompleted, datasetFaulted, datasetPercentage) => {
+
+								if (datasetCompleted) {
+									mLabelText.text = "Dataset Upload Complete";
+								} else if (datasetFaulted) {
+									mLabelText.text = "Dataset Upload Faulted";
+								} else {
+									mLabelText.text = "Dataset Upload: " + datasetPercentage.ToString ("F2") + "/1.0";
```
Comment (y22ma) [inline Assets/Placenote/Examples/PlacenoteSampleView.cs:238]: Use string.format is probaly a better choice

File: Assets/Placenote/Examples/PlacenoteSampleView.cs [hunk 3]
```diff
@@ -265,6 +285,22 @@ public void OnNewMapClick ()
...
+		if (mReportDebug) {
+			LibPlacenote.Instance.StartRecordDataset (
+				(completed, faulted, percentage) => {
+					
+					if (completed) {
+						mLabelText.text = "Dataset Upload Complete";
+					} else if (faulted) {
+						mLabelText.text = "Dataset Upload Faulted";
+					} else {
+						mLabelText.text = "Dataset Upload: " + percentage.ToString ("F2") + "/1.0";
```
Comment (y22ma) [inline Assets/Placenote/Examples/PlacenoteSampleView.cs:298]: see above

**Review by y22ma — APPROVED** [review]
